### ISSUE TITLE
support multiple openhab server

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab-android#10]
In case you got more than one openHAB server this app is not very usefull.

I am using a separate openhab server for developing.
It is not nice to change the URL in the settings each time I want to use the other server.
##

**Comment by kidalabama** [comment]
[](https://play.google.com/store/apps/details?id=treehou.se.habit)

**Comment by Alpoy** [comment]
I have 2 different OH servers (one for my house and one for the cabin) would be very nice to see this feature implemented!

**Comment by mueller-ma** [comment]
When every oh server is in the same network you can assign it to the same IP or dns name

**Comment by FlorianSW** [comment]
I alredy thought about implementing such a functionality. However, it would probably a bit easier, once #562 is merged (I would start working on this after #562). The UI I had in mind so far was pretty similar how GMail does it with different e-mail accounts (providing a switch in the flyout menu).

However, some things we need to consider:
* The connection settings would need to be moved into a database, instead of preferences itself (this could be done before, as a preparation step, which is already quite big I think)
* We would need to try to register the device using GCM for each "remote" connection, even if it is not selected in order for notifications to work
* I would say, that discovering the OH instance to connect to is pretty difficult with more than two servers (and probably takes a long time, as timeouts would be applied to each try), so it's possible that, during development, this feature needs to go (?)

That are my thoughts so far :)

**Comment by mueller-ma** [comment]
> I would say, that discovering the OH instance to connect to is pretty difficult with more than two servers

Currently if you have more one server, a random server is discorvery. Probably that one, which response faster.

**Comment by FlorianSW** [comment]
Uh, I haven't thought about that, my point with "discovering" was: When you start the app, it automatically selects if it connects to the local or remote server, which is based on the current network. If you've multiple servers in your configuration, the app probably selects a matching server randomly (if multiple remote and/or local servers are configured). So, I misused the term "discovery" here, sorry :)

**Comment by mueller-ma** [comment]
As a workaround you can use the stable version for one server and the beta for another one.

**Comment by curlyel** [comment]
> Autoconnect to the last used instance.

Agree 👍 
If this is not the right instance, the user should choose from the options menu to connect to another openHAB instance in case she needs to switch over to some other instance. 

So we need to maintain a number of openHAB connection peers (local+remote-Url settings + the needed credentials).

I'd suggest to **assign an `instance id`** or **a `configuration slot id`** to each configuration "slot". This id clearly identifies the meant openHAB instance and can/should be used in the 

- shortcut/widgets
- NFC tags
- BLE beacon broadcasts (once available https://github.com/openhab/openhab-android/issues/213 )

So the NFC tag could be written with:

`openhab://<configuration slot id>/<sitemap id>/<frame id>
`
e.g.
`openhab://1/main/0003>
`

Once we get **BLE beacon sitemap selection support** as proposed in https://github.com/openhab/openhab-android/issues/213, we may consider using the Eddystone URL to broadcast configuration slot id/sitemap/frame id. Unfortunatly, Eddystone URL is limited to 18 characters AFAIK. So the sitemap id has to be quite short to fit. 

And: The URL has to start with "http://" or "https://". So simply writing the above NFC string `openhab://....` wont work. But e.g. this works:

![20191020_155118](https://user-images.githubusercontent.com/11849305/67160878-6db72680-f355-11e9-9ddc-fc35a32c739f.jpg)

where:
```
oh = indicates openHAB use
1 = configuration slot id
main = sitemap id
0003 = frame id
```

**Comment by MarcusWolschon** [comment]
You'r overengineering this.
A simple selection is all that is needed.
THEN it can be improved in future features.

**Comment by curlyel** [comment]
> You'r overengineering this.

Why?
I guess you're referring to the `configuration slot id` - right?
I think, this is **important to have an indication**, which openHAB instance is targeted by the widgets/NFC/etc. If not included, they may point to something (sitemap/item) which might not be valid in the current selected openHAB instance ...

> A simple selection is all that is needed

Yes. That's the base function: Provide the option to configure a number of _configuration sets_ and add a selection to chose from them.

**Comment by MarcusWolschon** [comment]
> > You'r overengineering this.
> 
> Why?
> I guess you're referring to the `configuration slot id` - right?

No about NFC tags and BLE beacons while support for multiple servers AT ALL doesn't exist yet.

**Comment by curlyel** [comment]
Mmhh...

> * shortcut/widgets
> * NFC tags

... are **yet-existing features** of our openHAB-android app. I assume you are aware of it.

When we think about implementing  a "multiple server configuration" option, we should start thinking how this affects other features _before_ start coding. Aggree?

That's what _I_ was trying .... ;-)

_Just lean back an think about it for a minute:
What would you expect when you tap on a homescreen widget of your Android pointing to a specific sitemap/frame. Your expectation would be quite likely: "The openHAB-android app opens and shows exactly that sitemap/frame which you have made the widget for". It's mine too. AND: This is how it works today_

_Once you have "**multiple** server configurations", you may have **multiple** homescreen widgets pointing to the different sitemaps **out of these multiple servers**. I guess you would expect that our app will select the _right_ (correct) server connection and not just throw an error like "Sitemap not found"._

_(NFC is exactly the same story, just replace "homescreen widget" by "NFC tag" in the above section)_

That's why I came to my thought:

> is **important to have an indication**, which openHAB instance is targeted by the widgets/NFC/etc. If not included, they may point to something (sitemap/item) which might not be valid in the current selected openHAB instance ...

My guess is, the developers/maintainer would prefer a solution which **does not break existing features** or make them prone to errors. From my point of view, the `configuration slot id` (or whatever this is named) solves the need.

Maybe you have a more elegant and less intrusive way to solve this without the need for an additional identifier?

Feel free to explain ...
