### ISSUE TITLE
HABDroid tablet UI concept proposal

### ISSUE THREAD

**Issue by netwolfuk** [openhab/openhab-android#101]
I've been thinking about a more tablet focused UI, and taking HABDroid's UX even more into the Material design space. Specifically taking advantage of animations between fragments and UI colour changes based on the context.

![HABDroid UI Concept](https://netwolfuk.files.wordpress.com/2015/04/openhab_ui_concept_anim.gif)

I mocked up the above design in Photoshop and animated it in Synfig. It introduces a few new concepts which would need to be supported in OpenHAB.
- A grid view and a lot more control over layout and colour
- Changing colour schemes between fragments
- Animation of the selected item and fragment transitions
- Automatic execution of Item state changes
- An “Intent” Item which allows starting another Android application via an Intent

I've written [a blog post](https://netwolfuk.wordpress.com/2015/04/30/habdroid-ui-concept-openhab-for-android/) about it, where I expand on the concepts and start to present how I think they could be accomplished. There is still a bit to figure out, but it could serve as a good starting point for discussion.

I've closed commenting on that post on Wordpress, to encourage all discussion to happen here instead.
##

**Comment by kaikreuzer** [comment]
Hi @netwolfuk,

Your mock-up looks great, thanks for your ideas and input!
I'd very much like to see such features available in the Android openHAB app.

A bit feedback to think about from my side:
- Currently, the sitemaps are defined in a way that they are UI (OS) independent - the same sitemap is read by the ClassicUI, the iOS app and the Android app (and others). Your suggested extensions would imho break this concept, i.e. the sitemap would only make sense for Android.
- A huge step forward in UX terms would also be to allow customization through the user, i.e. adding or moving widgets etc. This is not possible with the static sitemap concept that we have.

I would like to address both points within Eclipse SmartHome (and thus openHAB 2) by a new, more flexible sitemap concept, which allows UI specific content (and thus make single sitemaps only work for certain clients) and to easily change the structure and content of a sitemap through the REST API. I have started a thread about this here: https://www.eclipse.org/forums/index.php/t/1064113/

I think this is what you would need for your Android app extensions as well. So my suggestion would be to work on these features for openHAB 2 and not trying to get this into openHAB 1 anymore. The Android app is anyhow designed in a way that it supports both versions of the runtime, so on this end there should be no problem.

Btw, wouldn't the same stuff apply to the iOS app as well...?

**Comment by netwolfuk** [comment]
Hi @kaikreuzer . 

Thanks for your response and for pointing out the OpenHAB 2 possibilities. Flexible site maps seems like an elegant approach to the multiple client conundrum. I'll look at converting my home setup to OH2. Is it ready for production yet? Is the new sitemap support on a milestone somewhere?

I'll have a think about what to post to that eclipse thread, but it will probably be a reiteration of what I stated on the blog entry.

**Comment by kaikreuzer** [comment]
> I'll look at converting my home setup to OH2. Is it ready for production yet?
> 
No, I consider it alpha, mainly because there are still many changes ongoing. But it is in a perfect state to add new features at the moment :-)
> Is the new sitemap support on a milestone somewhere?
> 
There is no schedule, it all depends on how much interest is there and who finds time for it. I’d like to follow up on it soon as Chris is also waiting for this for HABmin.
> I'll have a think about what to post to that eclipse thread, but it will probably be a reiteration of what I stated on the blog entry.
> 

No need to repeat yourself, maybe simply post a link to your blog. But you might want to involve yourself in the future discussion about how exactly this new sitemap concept should be designed.

Best regards,
Kai

**Comment by gersilex** [comment]
Rather than starting an Android intent, we could also make use of the intent filters of other apps. This makes it possible to "open" URLs which will be detected by the other apps.

This is the default behaviour of apps like
- Android market (market://* links, http(s)://play.google.com/*)
- YouTube (http(s)://*.youtube.*/*)
- Yatse (the XBMC remote) (yatse://command/show/remote)

This will also work on iOS devices, possibly with other URLs, though. Maybe this is a good way of keeping balance between OS-dependent functionality and a versatile, OS-independent global sitemaps.

**Comment by joefrank25** [comment]
Aweomse UI concept!

**Comment by mueller-ma** [comment]
@netwolfuk Do you still want to make a PR with your tablet mode?
