### ISSUE TITLE
Provide some insights on the app structure

### ISSUE THREAD

**Issue by JohannesPtaszyk** [openhab/openhab-android#1182]
**Is your feature request related to a problem? Please describe.**
As a new contributer it is really confusing to me, how the app is structured.

**Describe the solution you'd like**
I as a potential contributer would like to see some graphics, descriptions and guidelines on how the app is structured and where to put my new code.

**Additional context**
I just wanted to get started contributing, but for me it is somehow weird how there are fragment classes in the activity classes (e.g. Settings). And sometimes there are fragemnts on its own.

**Comment by maniac103** [comment]
I think it would be more helpful if you ask specific questions instead of a general overview, because the latter still doesn't answer specific design decisions and is a lot of effort to create. It's much easier (at least from my side) to do this in a FAQ style.

As for your specific question:

> , but for me it is somehow weird how there are fragment classes in the activity classes (e.g. Settings).

[PreferenceActivity](https://developer.android.com/reference/android/preference/PreferenceActivity) is mostly deprecated, which is why we implement it as a holder for a PreferenceFragment as suggested by the linked docs. Because it's a simple holder, the settings activity contains almost no code.
MainActivity isn't that simple (and has a lot of code on its own), which is why the fragment class is separate there.

**Comment by JohannesPtaszyk** [comment]
Hmm okay, i will try to bring some questions up and maybe we can have like a FAQ. 
Would be nice to gather insights, so we can get new contributors on a decent knowlege level quicker.

So should I just contribute a markdown file with all questions in it? Maybe with the questions grouped by layer or feature?

**Comment by mueller-ma** [comment]
You can create a PR to CONTRIBUTING.md with a "FAQ" chapter and we try our best to answer your questions.

**Comment by JohannesPtaszyk** [comment]
Thanks, will do!

**Comment by JohannesPtaszyk** [comment]
Okay, I created a PR. I hope I did everything right, because it is my first PR ever on a github project.

**Comment by mueller-ma** [comment]
You can add "Closes #1182" to the commit message, so GitHub can create a link between this issue and the PR and auto-close the issue when the PR is merged.

**Comment by JohannesPtaszyk** [comment]
Okay, so once we got all the answers from you guys together, I will just add them to my branch and we can merge it? Or do you want to handle it differently?

**Comment by JohannesPtaszyk** [comment]
Okay, I added your answers to the FAQ 👍 A

**Comment by JohannesPtaszyk** [comment]
Improved the things you mentioned.

**Comment by JohannesPtaszyk** [comment]
Added another adjustment-
