### ISSUE TITLE
Does not send basic authentication for access to events (reverse proxy)

### ISSUE THREAD

**Issue by sidamos** [openhab/openhab-android#1212]
### Actual behaviour
I am using openHAB 2.4 behind a reverse SSL proxy with basic authenticaion. I can see in the Apache logs that the app does not send the credentials for this URL:

"GET /openhab/rest/sitemaps/events/0280f475-925e-463f-9227-202b094a7bd0?sitemap=default&pageid=default HTTP/1.1" 401 442

This does not happen when using the Chrome browser to access the Basic UI.

### Expected behaviour
The app should always send the credentials (or react properly to the 401).

 
### Steps to reproduce
1. Set up reverse proxy with Apache and Basic Authentication
2. Point the app to that remote URL

### Can you reproduce the issue in demo mode?
No.

#### Client
* Android version: Pie
* Device model: Xiaomi Redmi Note 5
* Stock or customized ROM: Custom, Pixel Experience
* App version : 2.5.0
* Build flavor : Play Store
* Device language: German

#### Server
* Server version: 2.4.0
* Reverse Proxy: Apache
* Authentication method : Basic Auth

#### openHAB Cloud
N/A

#### App log
```
There is no such option!?
```

#### openHAB Server log
```
Nothing in that log.
```

#### Reverse Proxy log
```
Insert your reverse proxy error log here.
For nginx: `/var/log/nginx/error.log`
For Apache 2: `/var/log/apache2/error.log`
```
Nothing in that log.
```
"GET /openhab/rest/sitemaps/events/0280f475-925e-463f-9227-202b094a7bd0?sitemap=default&pageid=default HTTP/1.1" 401 442
```

**Comment by sidamos** [comment]
Also happens with 2.5.14-beta.

**Comment by MaxMaier1** [comment]
Hi,
I am still facing this issue regardless of the latest PlayStore or GitHub build.

Client:

- Android version: Oreo
- Device model: Huawei P20 Pro
- Stock or customized ROM: Stock, but rooted
- App version : 2.7.16-beta
- Build flavor : GitHub
- Device language: English

**Comment by mueller-ma** [comment]
@MaxMaier1 Can you post the logs of the webserver?

**Comment by MaxMaier1** [comment]
> 
> 
> @MaxMaier1 Can you post the logs of the webserver?

Sure, sorry I forgot.
I am running openHAB 2.4.0-1 behind an Apache reverse proxy, the configuration looks like this, which seems fine to me:
```
ProxyPass / http://127.0.0.1:8080/
ProxyPassReverse / http://127.0.0.1:8080/
<Location />
    AuthType Basic
    AuthName "OpenHab2 Restricted"
    AuthUserFile /etc/apache2/.htpasswd
    Require valid-user
</Location>
```
The sample user I am using to connect is called "test".

Local connections works without problems:
`/var/log/apache2/error.log`
```
192.168.178.85 - test [27/Jul/2019:11:41:04 +0200] "GET /rest HTTP/1.1" 200 1418 "-" "openHAB client for Android"
192.168.178.85 - test [27/Jul/2019:11:41:04 +0200] "GET /rest/sitemaps HTTP/1.1" 200 620 "-" "openHAB client for Android"
192.168.178.85 - test [27/Jul/2019:11:41:04 +0200] "POST /rest/sitemaps/events/subscribe HTTP/1.1" 200 546 "-" "openHAB client for Android"
192.168.178.85 - test [27/Jul/2019:11:41:04 +0200] "GET /rest/sitemaps/default/default HTTP/1.1" 200 1930 "-" "openHAB client for Android"
```

However connecting from without my networks results in 401 errors:
```
193.176.86.130 - test [27/Jul/2019:11:34:45 +0200] "GET /api/v1/settings/notifications HTTP/1.1" 404 3894 "-" "openHAB client for Android"
193.176.86.130 - test [27/Jul/2019:11:34:45 +0200] "GET /rest HTTP/1.1" 200 4807 "-" "openHAB client for Android"
193.176.86.130 - test [27/Jul/2019:11:34:45 +0200] "GET /rest/sitemaps HTTP/1.1" 200 665 "-" "openHAB client for Android"
193.176.86.130 - test [27/Jul/2019:11:34:45 +0200] "POST /rest/sitemaps/events/subscribe HTTP/1.1" 200 573 "-" "openHAB client for Android"
193.176.86.130 - - [27/Jul/2019:11:34:45 +0200] "GET /rest/sitemaps/default/default HTTP/1.1" 301 654 "-" "openHAB client for Android"
193.176.86.130 - - [27/Jul/2019:11:34:45 +0200] "GET /rest/sitemaps/default/default HTTP/1.1" 401 766 "-" "openHAB client for Android"
193.176.86.130 - - [27/Jul/2019:11:34:45 +0200] "GET /rest/sitemaps/events/c65c8cfa-e2ed-49e1-b438-f366c4bb34d8?sitemap=default&pageid=default HTTP/1.1" 301 776 "-" "openHAB client for Android"
193.176.86.130 - - [27/Jul/2019:11:34:46 +0200] "GET /rest/sitemaps/events/c65c8cfa-e2ed-49e1-b438-f366c4bb34d8?sitemap=default&pageid=default HTTP/1.1" 401 915 "-" "openHAB client for Android"
```
I assume the Authorization header is not sent along with the requests to `/rest/sitemaps/default/default`.

**Comment by mueller-ma** [comment]
Does the sitemap load on both local and remote network or do you get any error?

**Comment by MaxMaier1** [comment]
Besides
```
07-30 18:07:34.835 23113 23113 D PageConnectionHolderFragment: org.openhab.habdroid.util.HttpClient$HttpException: Unauthorized
```
in the Android app's log I can't find anything useful.

The sitemap including it's items is correctly displayed when connecting locally.
Using remote connection the sitemap's label is resolved correctly, but instead of the items I get the "Authentication failed" error message.

Temporarily disabling authentication in my apache config doesn't cause this error and the sitemap is displayed correctly using remote connection.

**Comment by mueller-ma** [comment]
Did you enter password and username for the remote connection?

**Comment by mueller-ma** [comment]
I tested this with my nginx reverse proxy and basic auth: No `401` in the logs. I'm using this config:
````
server {
    listen                                    80;
    server_name                               redacted.local;

    location / {
        proxy_pass                            http://localhost:8080/;
        proxy_set_header Host                 $http_host;
        proxy_set_header X-Real-IP            $remote_addr;
        proxy_set_header X-Forwarded-For      $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto    $scheme;
			auth_basic                            "Username and Password Required";
			auth_basic_user_file                  /etc/nginx/.htpasswd;
    }
}
````

Can you try to add the headers in Apache? And can you enable debug logging in the app (last option in settings)?

**Comment by fapgomes** [comment]
Hi, i've the same problem with apache mod_proxy.

**Comment by fapgomes** [comment]
Ok, the problem is when the network where the app is, have a transparent proxy or something like this.

**Comment by fapgomes** [comment]
For clarify, if I use a web browser it works, only the app fails.

**Comment by mueller-ma** [comment]
Can you post your apache config here?

**Comment by fapgomes** [comment]
Yes, but I've a new data. It's works with 3G/4G network in the mobile phone, when connected with WI-FI doesn't work. In the browser works every time.

My configuration is:

<Proxy "*">
   Options +ExecCGI
   AddHandler cgi-script .cgi
   AuthUserFile /etc/confs/users
   AuthGroupFile /dev/null
   AuthName "Auth"
   AuthType Basic

   <RequireAny>
        Require ip 192.168.1
        Require valid-user
   </RequireAny>
</Proxy>

SSLProxyEngine On
SSLProxyCheckPeerCN Off
ProxyPass / "https://localhost:8443/"
ProxyPassReverse / "https://localhost:8443/"

**Comment by mueller-ma** [comment]
Can you add `ProxyAddHeaders On`?
Can you also clear the app log, enable debug logging, reproduce the issue and post the log here? You can do this with the last two options in the settings menu in the app.

**Comment by fapgomes** [comment]
I added the proxeaddheaders on, but the result is the same.

I attach the two files, wifi.log, doesn't work (connected with wifi), 4g.log works (connected with 4G network).
[4g.log](https://github.com/openhab/openhab-android/files/3729897/4g.log)
[wifi.log](https://github.com/openhab/openhab-android/files/3729898/wifi.log)

**Comment by mueller-ma** [comment]
Do you still have this issue with 2.10.13-beta or later?

**Comment by m0rgano** [comment]
I can't get the OpenHAB app to connect to my Nginx reverse proxy remotely either. The connection works OK from the Chrome browser.
I think the problem may be I am using SSL encryption. The public key doesn't seem to install correctly in the app, even though I can install it from the phone's 'Other security settings'. Interestingly, installing from the app displays a 'toast' indicating success, but 'SSL client certificate' still shows 'None'. 
If I remove authentication (by commenting out the 'auth-basic...' lines in my nginx config file) it connects fine.
Behaviour is the same on 2.10.20-beta

**Comment by mueller-ma** [comment]
> The public key doesn't seem to install correctly in the app

How do you know? If you connect to a server with an untrusted cert, it will show a dialog where you can accept the cert or not.

> 'SSL client certificate' still shows 'None'

The ssl client cert is a certificate that the client uses to authenticate against the server. It's a replacement for the user name and password and has **nothing** to do with the cert from the server.

>  I can't get the OpenHAB app to connect to my Nginx reverse proxy remotely either.

Please go to settings, enable debug logging, view the log, clear it, go back to the main screen (the app tries to connect now). If you see an error message, please post the log here.

**Comment by m0rgano** [comment]
@mueller-ma My bad, I had 'openhabian' as the username instead of 'openhab', so it was a basic authentication issue. I discovered this by checking the contents of the Nginx log in /var/log/nginx on my OpenHAB server.
So, all seems to be OK - sorry for taking your time!

**Comment by hanzz** [comment]
I can also reproduce it. It happens only when SSL is used. If I switch to plain HTTP, the authorization header is sent everytime. I've tried to copy debug logs, but I was not able to click the "share" button in the corner. I will enable further debugging in httpd proxy to see what requests the app sends.

I will also try to check the code :), let's see ;).

**Comment by hanzz** [comment]
@mueller-ma, I think I know what's going on here. I've been using redirect in apache httpd from http to https and I used http:// scheme in remote hostname in openhab app. The openhab app then contact httpd using HTTP with Authorization header, httpd redirected it to HTTPS, but OkHttp does not include Authorization header in this redirected request and httpd returned 401.

The workaround for me was simply using "https". I also had to stop using local access with "http", otherwise openhab app would never try to use remote access (because it contact local hostname on "http" and this returned 401 so it did not try checking remote access hostname).

**Comment by hanzz** [comment]
Probably proper fix would be to stop handling redirects in OkHttpClient and handle them in the openhab app code directly. See https://github.com/square/okhttp/issues/2937 for the same issue.

**Comment by maniac103** [comment]
> I also had to stop using local access with "http", otherwise openhab app would never try to use remote access (because it contact local hostname on "http" and this returned 401 so it did not try checking remote access hostname).

Can you elaborate on this? As long as the local server(’s specified port) is reachable, remote access is never considered. How does it relate with 401 being returned then?

As for the actual problem, interesting finding ... I'll look into it.

**Comment by hanzz** [comment]
Hm, that means I need to tell you my full story :).

- I had openhab running locally only, using only plain HTTP. I used "local connection" to connect openhab. This worked as expected.
- I then received public IP from my ISP and configured openhab to run behind the apache httpd proxy and also configured HTTP to HTTPS redirect. I've also registered domain and changed the "local connection" to "http://openhab.domain.tld" and "remote connection" to "https://openhab.domain.tld".
- After that, openhab app stopped working, because it at first tried connecting to "http://openhab.domain.tld" and this redirected it to "https://openhab.domain.tld" which failed with 401, because during this redirect OkHttpClient dropped the Authorization header. It therefore never tried "remote access".

Thing to note is that "openhab.domain.tld" is accessible from both my local network and public internet, so it does probably does not make sense for me to use both "local connection" and "remote connection", because I need to have the same values in both of them (https://openhab.domain.tld).

**Comment by maniac103** [comment]
> Thing to note is that "openhab.domain.tld" is accessible from both my local network and public internet, so it probably does not make sense for me to use both "local connection" and "remote connection", 

Indeed. In that scenario, you only should set up the remote connection and leave the local one empty. Everything will work as expected then, as the remote connection will be used if there's no local connection set up. Alternative: keep remote connection as-is and use the local (LAN) IP for the local connection. That will work as well.

**Comment by hanzz** [comment]
I played with it a bit more and found out another possible reason why this might be broken the way described in this issue:

If you setup httpd proxy listening on HTTPS (port 443), but you proxy to openhab using HTTP (port 8080), then initial request to `https://domain.tld/rest/sitemaps/` is really sent to HTTPS port by openhab app. But because Openhab server handles that on 8080, it will return `"link": "https://domain.tld/rest/sitemaps/default/default",` and Openhab app apparently uses that "link" for further requests and it will start using HTTP. I think this is just server misconfiguration, but maybe it will help someone :).

You just need to proxy https requests to openhab port 8443 really. Proxying https requests to 8080 will result in these errors.

**Comment by mueller-ma** [comment]
> I played with it a bit more and found out another possible reason

Which reverse proxy are you using? You need to set a few headers to fix this issue. The config I posted in https://github.com/openhab/openhab-android/issues/1212#issuecomment-517394655 works for me in nginx.
