### ISSUE TITLE
Problem opening pinned sitemap

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab-android#1371]
First, thank you for the improvment!
Related to #1357 

### Actual behaviour
Pinning a sitemap widget to the homescreen works. Opening the shortcut, the page loads fine. However, opening a subpage causes the app to load but not display any new content. The expected content is shown when pressing the back-button.

### Expected behaviour
Pinned sitemap should function just like navigating to the page
 
### Steps to reproduce
1. Open sitemap in app
2. Long press widget with sub-items and pin to home screen
3. Close app
4. Open the shortcut
5. Click on a widget with sub-items
6. Wait for the loader to finish [content will not change]
7. Press back-button [content will change]

### Can you reproduce the issue in demo mode?
Yes, when pinning 'Ground floor' for example.

#### Client
* Android version: 9
* Device model: Xiaomi Mi 9
* Stock or customized ROM: stock
* App version : 2.7.1-beta
* Build flavor : Full
* Device language: German

#### openHAB Cloud
* openHAB Cloud version: 
* Self hosted cloud or myopenhab.org: myopenhab.org
* Authentication method : 

#### App log
Could not share - button disabled and text could not be selected.

**Comment by maniac103** [comment]
I can reproduce, and I thinthis seems related k the way we currently do NFC/shortcut invocations is fundamentally broken. Instead of opening a temporary page (which we currently do), I think we should treat it as normal page stack update, either
- keeping the root page as stack root or
- using the NFC/shortcut page as page root.

I think the latter is preferable, as it makes more sense for both back navigation and dual-pane view.
