### ISSUE TITLE
Add docs for Settings> Item name prefix

### ISSUE THREAD

**Issue by openhab-5iver** [openhab/openhab-android#1587]
The [documentation](https://www.openhab.org/docs/apps/android.html) does not mention what this setting is used for. I assume it is used as a filter in a REST API call, which could provide a performance improvement (we have 1684 Items)? Also, the value is not displayed once it is set, like is done for the CallState (I have it currently set to "Phone_")...

![image](https://user-images.githubusercontent.com/21967853/66219267-da190100-e698-11e9-9760-76a91ead9f21.png)

**Comment by maniac103** [comment]
It's not used as a filter, but as a prefix ;-) Suppose you have the alarm clock item bane set to 'AlarmClock' and the prefix is set to 'Phone_', the alarm is uploaded to item 'Phone_AlarmClock'.

**Comment by openhab-5iver** [comment]
In that case, I change my request to remove it entirely, since the functionality is simplified without it! :smile:

**Comment by mueller-ma** [comment]
> In that case, I change my request to remove it entirely, since the functionality is simplified without it! 😄

No, it's not: If you have only one phone, you can ignore the prefix at all. If you have two or more phones, you just enter the phone name as prefix and don't have to change the item names for alarm clock and call state.

**Comment by mueller-ma** [comment]
> Also, the value is not displayed once it is set, like is done for the CallState (I have it currently set to "Phone_")...

In #1589

**Comment by openhab-5iver** [comment]
> No, it's not: If you have only one phone, you can ignore the prefix at all. If you have two or more phones, you just enter the phone name as prefix and don't have to change the item names for alarm clock and call state.

@mueller-ma, I find it offensive and rude that you would close this issue without discussion and before an appropriate resolution. I took time out of my day to point out multiple gaps in the app that _you_ are maintaining. You've introduced unneeded functionality without documentation that makes the app needlessly complex and confusing, and in a best case will save the user from typing a few characters!

**Comment by maniac103** [comment]
From a complexity point of view, @openhab-5iver certainly has a point. The usefulness of the option probably depends on how many additional item upload features we'll add in the future...however, I can't think of that many additional options at the moment, so while I don't have a strong opinion on the topic, I'd be fine with removing the option.

**Comment by mueller-ma** [comment]
> I took time out of my day to point out multiple gaps in the app that you are maintaining.

Thanks for your feedback. The prefix not being displayed in the summary will be fixed in #1589.

> You've introduced unneeded functionality

Please have a look at my comment in the PR, that introduced the alarm clock feature: https://github.com/openhab/openhab-android/pull/1137#issuecomment-457295314
IMO it simplifies the setup: Just enter a different prefix on each device and turn on the features (alarm clock, call state) you want.
I agree that there are currently not many things that are sent to the server, but IMO it's better to keep this setting instead of removing it and maybe re-introduce it later, when there are more things to send.

> functionality without documentation 

I can add a sentence about this to the preference summary. How about "The Item names of the following features have no prefix. You can add one to differentiate between multiple devices"?

> The usefulness of the option probably depends on how many additional item upload features we'll add in the future...however, I can't think of that many additional options at the moment

Adding new features got slowed down by the background broadcast receiver restrictions from Android 8.
At some point I'd like to add sending the battery state to the server, but I'm not sure about the best way to do so:
1. Send battery charge percentage every 2 hours (or so). The delay can be shortened to 15 minutes while charging.
2. (Maybe also) start a foreground service listening for [ACTION_BATTERY_LOW](https://developer.android.com/reference/android/content/Intent.html#ACTION_BATTERY_LOW) and similar broadcasts.
