### ISSUE TITLE
Send -Do Not Disturb mode state- to openHAB

### ISSUE THREAD

**Issue by Schack17** [openhab/openhab-android#1663]
### Is your feature request related to a problem? Please describe.
No. But its similarly to "Send alarm clock to openHAB" openhab#1137 and "Send call state to server" openhab#1512 

### Describe the solution you'd like
If the "Do Not Disturb mode state" changed on my android phone the state should stored in a server item value.

### Describe alternatives you've considered
No idea.

### Additional context
It could be a string item like CallState and can contain the modes: "" for off, SILENT, ALARM_ONLY, VIP_ONLY or so.
Another Item can contain the configured end time of the mode like alarmClock. If the end time is not set, it could be a very high timestamp.

**Comment by freddy4711** [comment]
Hi guys. 

I really like the idea of having the DND state in OpenHAB to react on it. But what is the reason of having this new feature as a "Schedule-Based" trigger instead of a "Event-Based" Trigger? 

My idea is to react on that state and mute other devices in my smarthome as well. In my opinion, it make more sense, to have it "Event-Based", because if the state has been set on the device now and OpenHAB get this information 1 hour later, this might be useless in my opinion.

What do you think about that?

**Comment by maniac103** [comment]
> But what is the reason of having this new feature as a "Schedule-Based" trigger instead of a "Event-Based" Trigger?

The reason is there not being an event we can listen to for triggering the Item update ;-)

Yes, it would make much more sense to have this event based (applies to other stuff, e.g. WiFi SSID, as well), but if there's no event for it, we can't do it.

**Comment by mueller-ma** [comment]
> But what is the reason of having this new feature as a "Schedule-Based" trigger instead of a "Event-Based" Trigger?

There's a PR that'll add a setting to make all schedule based items event based: https://github.com/openhab/openhab-android/pull/2082
