### ISSUE TITLE
Disable demo mode if local instance is found

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-android#179]
I heard many people being irritated by being connected to the demo server after having setup their openHAB instance and launching the app for the first time. Since the local demo and the demo server are more or less the same, they often did not directly notice that they are looking at the remote demo instead of their local setup.
Since the demo server as many regular outages as well, I think it might be a good idea to automatically disable the demo mode (at least on the very first start of the app), if a local openHAB instance is found.

@digitaldan what do you think?
##

**Comment by digitaldan** [comment]
@kaikreuzer , sorry I missed this, I was thinking about this too why the app does not pick up a local openhab instance by default.

**Comment by ThomDietrich** [comment]
As this issue was referenced in another thread, I want to second the request for this improvement. I was also tricked by this behavior in the past.
Detecting a local instance sounds like a great idea. Independent of if a local instance was found or not I'd suggest to have a setup wizard guide the user through the process. The wizard could offer to work in demo mode, connect to the detected local instance, accept an additional global access path (domain / openHAB cloud / ...).

**Comment by kaikreuzer** [comment]
@digitaldan Would be lovely to see this covered in an upcoming app release :-)

**Comment by mueller-ma** [comment]
I'm on that
