### ISSUE TITLE
Use openHAB URL option

### ISSUE THREAD

**Issue by dustinthurston** [openhab/openhab-android#180]
An option needs to be available to always try to connect to local/primary url first.

The app has local and remote url options. I personally set the local url to a dns forwarding service and set the remote address to my.openhab. I use local https authentication as well. I find that whenever I'm connected to wifi, wherever I may be, the app uses the local url and performs very well. On mobile data, the app tries to connect to my.openhab only. The only reason I use my.openhab is for a few non-critical notifications and ifttt rules, which all seem to work when the app is connected to wifi. The problem: connecting through my.openhab is either painfully slow or the service is completely down. In the latter case, the app is useless.

Perhaps an alternative would be an alternate remote url and an option to use my.openhab for notifications/ifttt features only.
##

**Comment by hazzeh** [comment]
Right now the app only tries the local address if it is connected through wifi. Maybe it would be better to always try the local address first, if it is accessible, otherwise use the remote one.
Not sure how the performance will be affected.

**Comment by kaikreuzer** [comment]
> Maybe it would be better to always try the local address first

This completely defeats the idea of a local url. You would rather have a list of urls to try.

@dustinthurston: If I get you right, your real issue is that you need to "misuse" the remote url for the my.openHAB connection in order to have notifications working. I think we should rather split the app-notification support from the remote access part in my.openHAB as these are anyhow two pretty separate things.

**Comment by digitaldan** [comment]
@kaikreuzer that's an interesting idea, it might make sense to make the my.openhab configuration its own section in the mobile clients, with its own username and password, and then have options to use it for notifications and optionally for proxying connections.    That might be more clear to new users as they would not need to enter in the URL for my.openhab.

**Comment by kaikreuzer** [comment]
I would even like to have my.openHAB support OAuth2, so that you could simply activate "my.openHAB" in the app and grant access to the app in my.openHAB (and thus have different tokens that can be individually revoked (phone stolen?) in my.openHAB). With this, it would be clearly independent of any local/remote access url. (And anyhow, it does not make sense that people have to type in the my.openHAB url, it should have instead simply be an option to activate and the app can know by itself how to access it).

**Comment by dustinthurston** [comment]
@kaikreuzer and @digitaldan, Thanks for the thoughts and comments. You definitely understand the issue I'm describing.  @hazzeh also makes a good point that you probably don't want to waste time checking a "local" url when not connected to wifi.

@digitaldan, I was initially confused by the single username and password fields and ended up using my.openhab as both my local and remote url until I realized I needed to add the my.openhab username and password to my local users.

Any thoughts on how this change would impact the load on the my.openhab service? I use my.openhab as my remote url, so I'm putting a load on the server that I don't necessarily need (or want due to performance).

**Comment by dustinthurston** [comment]
In the mean time I'd like to ask (or beg) that the app always check "openHAB URL" first. Again, I find connecting through my.openhab to be painfully slow (at best) or it often doesn't work at all. I often have no remote access through the app. I keep trying to be patient thinking the bugs will get worked out with my.openhab, but that's not happening.

**Comment by mueller-ma** [comment]
It's intended, that the local url is only working on "local" networks (wifi and vpn). Also see #10.
