### ISSUE TITLE
Image items are not refreshing

### ISSUE THREAD

**Issue by kubawolanin** [openhab/openhab-android#2066]
### Actual behaviour

In 2.13.5-beta `Image` items with refresh interval set are not refreshing. The issue is not present in 2.13.0

### Expected behaviour
Image items should refresh properly.

 
### Steps to reproduce
1. Add an Image item with refresh interval (eg camera feed) to the sitemap
2. Open the sitemap in the app

The issue has probably originated in #2039 but I'm not sure.

**Comment by markusuidl** [comment]
This seems not to 100% solved.

I have my webcams on sitemap with refresh interval of 1000ms and it works.

But I have also statistic images of my photovoltaic and there refresh interval is at 1 minute. If I open the app the statistic images show old values and old time. I have to wait 1 minute, and then it refreshes. Or I swipe down to force an update, then a new image is shown.

So I think images have to be refreshed every time the site/frame is opened again. In an older version this worked and in the Playstore main release it works too I think.

**Comment by maniac103** [comment]
'Open' as in 'open from recents'? Or 'open with the app not running before'?

**Comment by markusuidl** [comment]
Will check this in the afternoon. Know what you mean. Will check the different scenarios.

**Comment by markusuidl** [comment]
Tested with version **2.13.9-beta** from playstore.


Made a php script to generate an image with timestamp.
```
<?php
$text = date("H:i:s");

header('Content-type: image/png');
$im = imagecreate(100, 30);
$bg = imagecolorallocate($im, 255, 255, 255);
$textcolor = imagecolorallocate($im, 0, 0, 255);
imagestring($im, 5, 15, 7, $text, $textcolor);
imagepng($im);
imagedestroy($im);

?>
```



Included image like this in my sitemap with a refresh of 10 seconds
```
Text label="Test" {
      Image url="http://127.0.0.1/bild.php"		refresh=10000
}
```


### Testing scenarios:

1. all apps closed **>** start app **>** navigate to Test **>** **old time / older than 10s** FAIL

2. stay on Test **>** send app to background **>** wait more than 10s **>** go back to opened app **>** directly refreshed OK

3. display turns off due to inactivity with Test opened **>** wake up with fingerprint **>** directly refreshed OK

4. navigate from other frame to Test **>** **old time** FAIL


### Conclusion:
it refreshes only after 10 seconds (as defined in sitemap) or when directly bringing back app to front and Test was open before.
It does not refresh when navigating between frames in the app.

*with directly refreshed I mean: time is not next 10s intervall but directly refreshed to current time, that's ok.

**Comment by maniac103** [comment]
Thanks, I'll check that.

**Comment by maniac103** [comment]
OK, found the issue: the HTTP request is fired at the correct time by the image view, but the response is served from (OkHttp internal) cache. I'll think about a solution.

**Comment by maniac103** [comment]
#2084 should fix this. Thanks again for the great reproduction test case!

**Comment by markusuidl** [comment]
Issue again in 2.13.17-beta. Image not refreshing when navigateing to frame/page.

Was working in 2.13.16-beta.

**Comment by maniac103** [comment]
I can not reproduce that (using the test case you posted above) on 2.13.18-beta. From the commit history, I don't see what could cause a regression there either.

**Comment by mueller-ma** [comment]
After rotating the device images don't refresh anymore.

**Comment by maniac103** [comment]
I rather see an issue that the image disappears completely after device rotation. Are you referring to that?
In any case, I'll have a look into that.

**Comment by mueller-ma** [comment]
The images don't disappear on my device, they just stop refreshing.

**Comment by markusuidl** [comment]
It's weird, can not describe a testing scenario.
Will investigate it.

Sometimes it doesn't update and sometimes it does not load and display white area instead.

**Comment by maniac103** [comment]
#2119 should fix this ... the issue was pretty subtle and only happened in a specific timing scenario (new WidgetImageView instance created after rotation instead of reusing an existing one + first layout pass happening after assigning image URL to WidgetImageView).
