### ISSUE TITLE
Display new openHAB 3 UI

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#2230]
### Is your feature request related to a problem? Please describe.
openHAB 3 comes with a new UI that isn't supported by the app.

### Describe the solution you'd like
It should be implemented like HABPanel.

### Additional context
https://community.openhab.org/t/plans-to-support-oh3-in-android-app/105346

**Comment by ghys** [comment]
Fyi: looking at the presence of a `runtimeInfo` property in the response to the root `/rest/` is IMO a good way of detecting OH3. OH2 doesn't have that.
```
{
  "version": "4",
  "locale": "en_US",
  "runtimeInfo": {
    "version": "3.0.0",
    "buildString": "Build #1929"
  },
  ...
}
```
(this info might even be useful to display for instance in the About page 😉)

**Comment by mueller-ma** [comment]
Currently the app uses the field `version` to know what the server is capable of. This should be used the the new UI as well, because the version was bumped from `3` to `4`.

> (this info might even be useful to display for instance in the About page 😉)

With multi server support we removed the version from about, see https://github.com/openhab/openhab-android/pull/1900#issuecomment-665492794:

> IMHO we can/should nuke the REST API version from the UI entirely. It's not immediately important or useful to the user anyway. I think it should totally be sufficient to put it in the log.

**Comment by mueller-ma** [comment]
I have a few questions regarding the new UI:

- How is the new UI called?
- Is this meant as a replacement for the sitemaps?
- Is the URL to the new UI just the server address, e.g. https://demo.openhab.org/ (if it would be oh 3)?

**Comment by ghys** [comment]
> How is the new UI called?

It doesn't really have a formal name, it's just "the main UI" or "the UI".

> Is this meant as a replacement for the sitemaps?

No, in fact it doesn't know how to show them currently (that feature exists but was not finished), and in fact I'm still unsure if it should - because that way it could be presented alongside the native-rendered sitemaps somehow without having 2 separate implementations (web & native) in the same app. You could still have the user choose a sitemap as the default page when the app is launched.
See https://github.com/openhab/openhab-webui/pull/259#issuecomment-632882344 for an interesting proof of concept in iOS.
Something should also be done with the different hamburger menus, the web UI has one and the Android app has one so if there's both displayed this could become quite confusing.
In the link above we discussed a way for the apps to have some interface with the UI via JavaScript (a global JS variable or similar) so for instance clicking on the "other apps" icons would trigger some native code instead of opening the right-side drawer. We could also add menu entries in the web UI's left drawer to navigate to native pages, etc.

> Is the URL to the new UI just the server address, e.g. https://demo.openhab.org/ (if it would be oh 3)?

Normally yes.

**Comment by mueller-ma** [comment]
> It doesn't really have a formal name, it's just "the main UI" or "the UI".

I proposed a PR and called the UI "openHAB 3 UI" there.

> Something should also be done with the different hamburger menus, the web UI has one and the Android app has one so if there's both displayed this could become quite confusing.

I added a comment to https://github.com/openhab/openhab-webui/pull/259#issuecomment-703317711

Do you think it's worth to add the new UI now or wait until the menus can be changed by the app?
