### ISSUE TITLE
Suggestion: allow the app to send the cell ID to get rough location

### ISSUE THREAD

**Issue by rolandmas** [openhab/openhab-android#2290]
I'd love if the app could send the current cell ID to the OpenHAB instance, just like it can send the current wifi ESSID. There are several cases where it would be useful (at least to me):
- trigger a presence item when approaching the house, and not only when entering it;
- keep the presence item on even when I'm in the garden and out of reach of the wifi;
- no need to put the whole house in away mode if I just popped out to the grocery store;
- and so on, probably.

I've seen #914, but it seems to be somewhat stale, so maybe this suggestion would provide a quick-fix in the meantime.

**Comment by mueller-ma** [comment]
This is most likely doable, but only quite advanced users may use it.
I once tried to implement sending the GPS location, but that requires some battery expensive actions. This could work better.

@maniac103 Do you see a reason why not to implement this?

**Comment by maniac103** [comment]
Yes,  I'm definitely not a fan for a variety of reasons:
- It doesn't work on CDMA phones (probably not much of a problem, LTE is widespread in the US now)
- It's an extremely technical feature (most users won't know their home cell ID)
- Since cell size varies so much depending on whether you're in a city or a rural region, the usefulness of the feature greatly depends on where you live
- It's a band aid, since what you want to know is whether you are in a certain place, not the cell ID
- Does updating the cell ID every hour or something really provide sufficient resolution, even if all of the above is not a problem?

IMHO the geofence solution definitely is the better one ... Maybe one shouldn't strive for the big solution (integrating with some geofence API on the server), but keep the scope smaller, e.g. by just allowing the user to define some geofences and then updating an item with the name of the geofence the user currently is at.
