### ISSUE TITLE
No creation of Homewidget for OH3 possible anymore with newest Beta

### ISSUE THREAD

**Issue by goofy1988** [openhab/openhab-android#2506]
### Actual behaviour
First Problem:
On my Tablet and on my Phone i cannot create any widget for the Homescreen anymore to directly access the OH3 Main UI. 

Second Problem:
With newest Beta there should be the possibilty to choose wich page want to be choosen to link to. But this plzs button is only available on the main overview page and not visible on other pages wich are created for example ( Heating, Bathroom etc)

### Expected behaviour
With newest Beta there should be the possibility to choose the preferred page and than pushing the plus sign top right to create a widget link to the preferred page. 

 
### Steps to reproduce
Open Openhab Beta App go to OH3 Main UI and push Plzs sign in the top right corner. Widget creation should appear but doesnt.

### Can you reproduce the issue in demo mode?
Yes. Exactly same misbehaviour.

Google Pixel 4XL Android 11

Xiaomi Mi Pad 3 Android 7

**Comment by mueller-ma** [comment]
> First Problem:
> On my Tablet and on my Phone i cannot create any widget for the Homescreen anymore to directly access the OH3 Main UI.

Will be fixed by  #2507.

> Second Problem:
> With newest Beta there should be the possibilty to choose wich page want to be choosen to link to. But this plzs button is only available on the main overview page and not visible on other pages wich are created for example ( Heating, Bathroom etc)

This must be changed server side. I was using an older version of openHAB 3 when I developed the shortcuts for subpages. In this version the main UI doesn't ask the app to be displayed in fullscreen and therefore the action bar of the app is always shown, including the shortcut button.
@ghys Can you add the shortcut button to every subpage of the main UI and HABPanel? I noticed that switching tabs (e.g. "Overview" and "Locations" on https://demo.openhab.org/) doesn't change the URL, so the cannot be the target of a shortcut. Is this something that could be changed as well, e.g. by adding a simple index to the url?

**Comment by ghys** [comment]
> @ghys Can you add the shortcut button to every subpage of the main UI and HABPanel?

The navbar would be getting a bit cluttered, but ok I'll consider it.

> I noticed that switching tabs (e.g. "Overview" and "Locations" on https://demo.openhab.org/) doesn't change the URL, so the cannot be the target of a shortcut. Is this something that could be changed as well, e.g. by adding a simple index to the url?

The home tabs are not "routable", that's true, because there were problems when I tried it, but I'll try again.

**Comment by politas** [comment]
>The navbar would be getting a bit cluttered, but ok I'll consider it

Perhaps a dynamic overflow menu when the bar is short?

**Comment by mueller-ma** [comment]
I opened https://github.com/openhab/openhab-webui/issues/1080 for this issue.
