### ISSUE TITLE
Order sitemaps alphabetically

### ISSUE THREAD

**Issue by kvoit** [openhab/openhab-android#270]
Especially in the app, sitemaps suggest themselves as the primary unit of order. Unfortunately, the order of sitemaps in the sidebar seems to be absolutely random with no possibility to influence it. Would it be possible to order the sitemaps alphabetically, at least?

**Comment by ldet** [comment]
Good idea
Sorting alphabetically schould be possible.

Currently the order is determined by the rest api.
We could sort them by their name (the filename) or the label defined inside the file. I personally think filename would work best, because we could do something like this to force a specific order:
`0Lights.sitemap`
`1Heating.sitemap`

On the long-term, we might want to consider adding an index attribute to sitemaps we can sort by:
`sitemap name label="label" index="0"{`
But this would need to be done elsewhere.
And even then alphabetically is a good fallback solution I think.

**Comment by lolodomo** [comment]
To be closed due to #392.

**Comment by mueller-ma** [comment]
I would go for alphabetic order with the sitemap label, since it is shown in the ui. Sitemaps are not meant for navigation, so IMO some kind of index is not needed.

**Comment by mueller-ma** [comment]
Will be fixed in #638
