### ISSUE TITLE
App doesn't show cyan label and valuecolors

### ISSUE THREAD

**Issue by Trysupe** [openhab/openhab-android#2878]
### Actual behaviour
In the sitemap configuration for basicui on Desktop you can use `cyan` as a `label`- and `valuecolor`. This is not possible in the openhab app. The text is displayed in white.

### Expected behaviour
Display the text in `cyan`

 
### Steps to reproduce
```
Text item=Heizung_DeltaT label="Blue" labelcolor=["blue"] valuecolor=["blue"]
Text item=Heizung_DeltaT label="Cyan" labelcolor=["cyan"] valuecolor=["cyan"]
```
On Desktop:
![image](https://user-images.githubusercontent.com/45742226/163346379-a4d0c13b-8c7c-49c4-bfd5-ad92e5aba911.png)
On Mobile:
![Screenshot_20220414-102825_openHAB](https://user-images.githubusercontent.com/45742226/163346540-e7ff58cf-8604-46ac-bdc7-1e9236590a04.jpg)

#### Client
* Android version: 12
* Device model: Samsung Galaxy S22 Ultra
* App version : `2.20.0`
* Build flavor : `Full`
* Device language: German

#### Server
* Server version: `2.5.12`

**Comment by maniac103** [comment]
Workaround: use `teal` for now (same color, just different name)

**Comment by mueller-ma** [comment]
There's a list of supported colors in the docs: https://www.openhab.org/docs/ui/sitemaps.html#label-and-value-colors

In addition the browser does also render all valid html colors. It would be a larger task to add all these colors to the app, because the colors may be changed based on the background: https://github.com/openhab/openhab-android/blob/main/mobile/src/main/res/values/arrays.xml#L49-L69

**Comment by Trysupe** [comment]
Didn't know that. Thanks=)
