### ISSUE TITLE
roller shutter items trigger instantly on scroll

### ISSUE THREAD

**Issue by cwihne** [openhab/openhab-android#3113]
### Actual behaviour
In released 2.23.0 and newest re-styled app 2.23.5-beta, roller shutters are triggered instantly when scrolling through the list with finger on controls (up, stop, down).

### Expected behaviour
As on any other type of control, a moving finger for scrolling should not trigger the underlying item, as this navigation leads to unwanted activities or value changes.

 
### Steps to reproduce
1. have roller shutter items in a sitemap, on a page with as many items that it exceeds screen height, so scrolling is needed
2. scroll by putting your finger on a roller shutter item control and move up/down
3. underlying item is triggered, roller shutter closes/opens, page content scrolls
4. do same manual navigation on other type of control, e.g. switch controls
5. switch is not triggered, but page content is scrolling
6. Selections are not opened on scroll gesture
7. subpages are not opened on scroll gesture

### Can you reproduce the issue in demo mode?
no value feedback visible on roller shutter in demo mode, so no idea if commands are triggered

#### Client
* Android version: 
* Device model: Samsung Galaxy S21
* App version : 2.23.0 and 2.23.5-beta
* Build flavor : apk download from github
* Device language: DE

**Comment by maniac103** [comment]
What about the color light sitemap entry, does that one trigger similarly for you?

**Comment by maniac103** [comment]
Note to self: might be related to `android:descendantFocusability`, but color and roller shutter are identical there.

**Comment by cwihne** [comment]
Interestingly they do not behave identical. The Color light sitemap entry behaves as I'd expect, so neutral in the case of scroll: When touching the screen on arrow button and start swipe up or down (=scroll), it does not change value. In case I release from screen fast (=tap), command is sent. In case of tap+hold, value is in-/decreased, depending on button direction.

**Comment by maniac103** [comment]
Oh, now I see. The roller shutter widget sends command [right on button touch](https://github.com/openhab/openhab-android/blob/main/mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt#L882-L884) instead of using click listeners [as the color widget is doing](https://github.com/openhab/openhab-android/blob/main/mobile/src/main/java/org/openhab/habdroid/ui/WidgetAdapter.kt#L1137-L1141). This behaviour goes back to commits 586d925afcf3320553b8af6180461cc784389d11 and 15881789862504596d992ed4d3a1f2d76f9da009 (the latter being 10 years ago!).
The reason for implementing it like this probably is the 'move-on-touch, stop-on-release' logic. I guess we still need a better trigger for this, though...

**Comment by mueller-ma** [comment]
> What do you think of 'start moving on either short or long press, stop moving on ACTION_UP if previously triggered by long press'?

Sounds good. AFAIK there are also some accessibility lint issues, because we use `View.OnTouchListener` and not `View.OnClickListener`.
