### ISSUE TITLE
Section switch not aligned with icon

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#3124]
### Actual behaviour
![image](https://user-images.githubusercontent.com/22525368/207127502-67bece49-dcec-45f8-9596-671e62466b3d.jpeg)

### Expected behaviour
The switch and the icon should be on the same height.

 
### Steps to reproduce
1. Have a switch with mappings and without label in the sitemap.

**Comment by maniac103** [comment]
That issue is hard to solve:
- the icon is top aligned, because if the text is visible, it should stay on top
- the icon and switches do not have the same height
- so even when converting the switch top margin to a label bottom margin, the alignment still won't be correct

The icon alignment would need to be changed based on whether the text is visible or not, but I don't see a proper way of doing that. (Proper meaning XML only here)

**Comment by mueller-ma** [comment]
For me it's fine to keep it as is.
