### ISSUE TITLE
Switch with mapping from "compact-mode" also in "non-compact-mode"

### ISSUE THREAD

**Issue by alltime84** [openhab/openhab-android#3191]
I personalty prefer the "non-compact-mode" as I think it is more structured and I got used to find the values below the label.
But the only widget that does not really fit into the design in my own opinion is the switch-widget having mappings. It looks nicer in the "compact-mode". Maybe because it is around 50% higher than other widgets in the "non-compact-mode"? At the same time I understand that sometimes it would be nice to fit a lot of text or options into the switch. Therefore I have two ideas:

1. If label and/or icon is set in sitemap: use the design of the "compact-mode"
2. If no label and icon is set in sitemap: use full line space as no label and icon is required

With those two options the line-hight could be the same as other widgets.
I added some screenshots to better explain my wish.

![Screenshot 2023-02-04 104038](https://user-images.githubusercontent.com/15026656/216768521-ea952777-bc82-412a-acd9-bfc67881174b.jpg)
![Screenshot 2023-02-04 104116](https://user-images.githubusercontent.com/15026656/216768522-079455de-4fdf-4054-bca7-b2a5992878a7.jpg)
![Screenshot 2023-02-04 134400](https://user-images.githubusercontent.com/15026656/216768524-863c68d7-c2c8-4dae-adf6-52135caebea4.jpg)

**Comment by maniac103** [comment]
The design goal of the non-compact mode was to work with *any* kind of label, value or (here) number of buttons. Your suggestion doesn't fulfill that goal ;-) (Imagine e.g. 4 buttons with some text on a smaller screen) I also don't see why/how the icon is related here? We need to keep space for icons anyway, since any other widget could have an icon.

If anything, what would make sense in my  view is extending the current special case for one button to two buttons, so if there's one or two buttons they're shown in the same row, otherwise in a second row.
(It's probably also why it looks weird in your view, it's optimized for larger amounts of buttons. It's not the height, because that one is the same as for the slider widget)

**Comment by alltime84** [comment]
regarding 1.: Yes, ok. It does not fulfill that. But I like the proposal to show the switch on one line if one one or two buttons are used.
regarding 2.: Ok I checked it. If the label and value are not used. The line-hight will be smaller. And you might be right, it might be more consistent to not use the space of the icon. 

I will close this idea...

**Comment by alltime84** [comment]
Idea does not fulfill design goal to show labels of any size
