### ISSUE TITLE
Sitemaps - add option to hide the icons

### ISSUE THREAD

**Issue by dilyanpalauzov** [openhab/openhab-android#3331]

**Comment by mueller-ma** [comment]
Basic UI has such a setting in Main UI.

**Comment by dilyanpalauzov** [comment]
Yes, but I want to have it independently in openhab-android.  Because sometimes the screen is not wide enough for icons, but on other times it is wide enough.

**Comment by mueller-ma** [comment]
Of course. My comment was meant as "Basic UI does this, so it's a valid feature request for the app".

**Comment by dilyanpalauzov** [comment]
There shall be diffenrent options, how to use the horizontal space, if it is not enogh, e.g. in Compact mode.  Like:

- if icons are generally shown, but an item has no icon, and there is not enough space for the label and value, then for this particular item start the label from the left-most position.

**Comment by maniac103** [comment]
> if icons are generally shown, but an item has no icon, and there is not enough space for the label and value, then for this particular item start the label from the left-most position.

Besides this looking ugly, it's not possible, because there's a dependency circle: the visibility of the icon affects the available space. Trying multiple layout passes (with and without icon) for checking whether or not there's enough space would be utterly complicated (if at all meaningfully possible); I highly doubt it would be worth the effort.
