### ISSUE TITLE
Dynamic icons for numeric values do only work with integers in beta version

### ISSUE THREAD

**Issue by SteWers** [openhab/openhab-android#3472]
### Actual and expected behavior
In version 3.7.3-beta (my be earlier) I recognized, that my temperature icons are not more _dynamic_ and only the default icon is displayed. In version 3.7.0 it is OK. In version 3.7.4-beta the problem persists. The Basic UI via browser is also OK.
As the temperatures are numeric values, I had a look to my switch values and they work as they should. Also the build-in icons are looking OK. In my case humidity.

This is from version 3.7.3-beta:
![image](https://github.com/openhab/openhab-android/assets/42718143/8088772e-d11e-42a9-836d-0f194bd2039d)

And so it looks in version 3.7.0 (green because it is a nice outside temperature):
![image](https://github.com/openhab/openhab-android/assets/42718143/9e4ec6b7-0896-4b59-bbde-1daaa56ccf9e)

Item definition:
```
Number Aussentemperatur "Temperatur draußen [%.1f °C]" {channel="mqtt:topic:mosquitto:Balkonlicht:Temperatur"}
```
Sitemap entry:
```
Text item=Aussentemperatur label="Außentemperatur [%.1f °C]" icon="temperature_outdoor"
```
Icons:
![image](https://github.com/openhab/openhab-android/assets/42718143/1f7d13f9-f0d1-442f-a336-8a029c9c36af)

 
### Steps to reproduce
1. Create own icons
2. Use the icons on a sitemap numeric item

### Can you reproduce the issue in demo mode?
I think, it is not testable in demo mode

#### Client
* Android version: 9 and 13
* Device language: german

#### Server
* Server version: 4.0.2 (Just updated to 4.1.0 M1; just the same)

#### openHAB Cloud
* myopenhab.org

**Comment by maniac103** [comment]
The logic for icon selection in core can be found [here](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.ui.icon/src/main/java/org/openhab/core/ui/icon/AbstractResourceIconProvider.java#L70-L105). What's visible from there is that
- a unit sent with the state is discarded on icon selection
- the first attempt is the raw numeric value (in your case `temperature_outdoor-20.1.png`)
- if that fails and the numeric value is between 0 and 100, the next value smaller than the numeric value is used (in your case `temperature_outdoor-20.png`)

(From the last point, it's visible that your case only works 'by luck' because your temperatures are in a value range that could also be a percentage - `temperature_outdoor--10.png` wouldn't work)

Having said that, I created a test item with type `Number:Temperature` and category `temperature`, added it to a sitemap, opened that in the latest Android app and modified the value from the Karaf console [1]. Additionally I enabled logging for the above logic (`log:set DEBUG org.openhab.core.ui.icon`). Resulting log:

```
2023-09-12 14:54:44.594 [DEBUG] [ui.icon.AbstractResourceIconProvider] - Use icon temperature.svg as temperature-5.0.svg is not found
2023-09-12 14:54:54.979 [DEBUG] [ui.icon.AbstractResourceIconProvider] - Use icon temperature.svg as temperature-5.1.svg is not found
2023-09-12 14:55:03.385 [DEBUG] [ui.icon.AbstractResourceIconProvider] - Use icon temperature.svg as temperature-5.1111.svg is not found
```

As far as I can tell, this is exactly as expected, the app sends numeric state as-is.

Then I changed the state description pattern to `%.1f %unit%`. Result for the same attempts:
```
2023-09-12 14:58:01.978 [DEBUG] [ui.icon.AbstractResourceIconProvider] - Use icon temperature.svg as temperature-5.0.svg is not found
2023-09-12 14:58:04.812 [DEBUG] [ui.icon.AbstractResourceIconProvider] - Use icon temperature.svg as temperature-5.1.svg is not found
```
As expected, as 5.1 and 5.1111 updates are collapsed into one now.

With state description `%d %unit%`, it's as expected again:
```
2023-09-12 14:59:34.844 [DEBUG] [ui.icon.AbstractResourceIconProvider] - Use icon temperature.svg as temperature-5.0.svg is not found
```
All 3 are collapsed into one now. (Before #3456 that collapsing didn't happen because the raw numeric state (e.g. '5.1111') was always sent, regardless of the state description.)

Having said that, I think we need more information here:
- Does it work correctly/as expected in BasicUI?
- If yes, can you enable logging for the icon code in core as mentioned above and see the log output for the fallback to the generic icon?

[1] `openhab:update NumberTest "5 °C"`, and afterwards with 5.1°C and 5.1111°C to test effect of decimal places

**Comment by maniac103** [comment]
> If you need more, I'll provide it in the evening.

No, it's obvious what happens: the state is split (`25,8` + `°C`) and the former is interpreted as floating point value, which fails due to being formatted in German format (`25,8`, while it should be `25.8`).
I'll look into it, this should be easy to fix. I couldn't reproduce it because the emulator I was testing this on is configured in English locale.

**Comment by maniac103** [comment]
See PR above, as expected it's pretty easy to fix once the issue is known. Thanks for testing the beta version :+1:

**Comment by SteWers** [comment]
You're welcome. Thanks for fixing so fast. I know, that it is important to get a hint to a bug.
If you release a new beta with the PR merged or when you can provide me an apk-file, I'll test it and close the issue.

**Comment by SteWers** [comment]
The problem is solved in the last beta. Thanks.
