### ISSUE TITLE
delay to reflect status on habdroid

### ISSUE THREAD

**Issue by laohixdxm** [openhab/openhab-android#351]
I switch On/off button on habdroid UI. say from off to on.
Sometimes It has delay to reflect status on habdroid.
When I slide switch,  say from OFF to ON.
I believe this is NOT device/binding specific. As I see same problem for both orvibo & zwave.

* device status change to ON.
* by browser, status change to ON immediately.
* by habdroid, status does NOT change to ON until next time UI update.
It seems to me Habdroid have periodic UI update for every 30 seconds.

Is this something normal? Should it be seen as a bug?
Thank you very much.

**Comment by lolodomo** [comment]
Is it only happening when you use certain bindings or for any switch ?
Please provide an example of sitemap where you have the problem.

**Comment by lolodomo** [comment]
Do you have your items in a frame that is inside another frame ? I think there is a problem in such a case and items are not refreshed in this case. I will create an issue if I can reproduce.

**Comment by lolodomo** [comment]
Frame in frame is not valid but supported by few UIs. It  is not (more or less) ignored by the openHAB app. So the problem is not on this side for you.
I try to reproduce using the demo sitemap and the item DemoSwitch and everything is immediately refreshed in the openHAB app when I update the switch in Basic UI.
So your problem seems to be a specific problem and not a general problem. You will have to do a better analysis first and provide more information so that we can reproduce it.

**Comment by mueller-ma** [comment]
Nested frames produce a warning in the oh log, so I think it's not supported.

**Comment by mueller-ma** [comment]
I have a minimal delay (~0.5 sec) between basic ui and app, when I change the state via karaf console.

**Comment by mueller-ma** [comment]
Issues like these should be gone with the SSE support. Please reopen if you still have this issue.
