### ISSUE TITLE
Some issues with Webview on Android

### ISSUE THREAD

**Issue by Togeole** [openhab/openhab-android#43]
Hello, 

I have the issues below with OpenHAB 1.6.1 and HABDroid 1.5.1.1.
Not knowing if they are linked, I prefer to open only one issue for the moment.

1) Issue with paths:
- I create a subdirectory under 'webapps' called 'test'.
- In this directory, I put 2 files:
  - index.html in which I use the line &lt;img src='image.jpg' alt='' /&gt;
  - image.jpg

It works asis in a Web browser but not under habdroid where the 'image.jpg' is not found (error 404).
- I create a directory called 'test' under the main 'test' directory.
- I put the 'image.jpg' file in it and I update the img src with 'test/image.jpg' (can be indifferently preceded by / or ./).

It works in habdroid and no more in a web browser. Same story with a js file as src of a script tag.
Workaround is to put the linked files in both webapps/&lt;maindir&gt; and webapps/&lt;maindir&gt;/&lt;maindir&gt;.

2) When using SSL, I receive blank pages in the webview either in local or in remote and with or without authentication enabled.

3) When using authentication in http (because blank page in https), I systematically get the error 401 either in remote or in local even with the webview url format http://user:password@&lt;openhab_server:port&gt;/webapps/test/
Note this last format is working with an image (in sitemap) generated by a cgi on an IP Cam protected by a basic authentication.

Many thanks in advance for your answer.
##

**Comment by elisman** [comment]
Same issue here. The thing is that HABdroid always tries to load widgets through proxy, without authenticating. No matter what webview I try to load, HABdroid requests it through proxy in the way:

GET /proxy?sitemap=default.sitemap&widgetId=02010400

The response is always Http code 401 as authentication is required. Then HABdroid stops.

GreenT i.e. sends the same request, probably with credentials, and gets code 200 as answer.

Any news on this? Or tips on how to force sending  credentials with the request?

**Comment by Togeole** [comment]
Hello, 

Unfortunately, no answer until here.

As workaround, even if it's not ideal, I removed the authentication for connections from local devices (LAN/local WiFi) and I open systematically a VPN when I want to connect remotely from my Smartphone before opening Habdroid. In Habdroid, both local and remote IP addresses are set with the local IP address.

Also note that, in OpenHab 2, the webapps folder does not exist anymore. I think that it means we will have to install a separate web server for personal developments that will communicate via REST. It seems there is no authentication issue with external web servers.

Vincent

**Comment by elisman** [comment]
Hi @Togeole,

thanks for your quick reply. In fact I have a separate apache server where i tried to locate the pages in and load them via an external URL. So, in fact, in openHAB 2 the problem will still be there as this is an issue with HABdroid and not with openHAB. If I try load "`https://google.com/`" in a webview I still get 401.

Your solution in LAN works also for me, but the VPN workaround is not really feasible. This should be fixed in HABdroid to send authentication information in the request and that's it. As written, all other UIs work well and load the widgets correctly. I also have a valid certificate installed in `jetty`.

Did anyone from the HABdroid team looked at the issue? I cannot imagine that we are the only ones having this issue.

I could also help with logs or testing if necessary.

Cheers,
Elisei

**Comment by thoern** [comment]
Hello,

I have the same problem. The combination:
habdroid Webview -> https -> ReverseProxy -> OpenHAB

does not work. In previos release (1.6 or lower) it worked. So probably something has changed/has been broken with 1.7

**Comment by elisman** [comment]
Hi,

I now have a separate Apache2 server that serves a webview, but without having an authentication configured. This now works only from external and not from my home network. I don't know why. HABdroid does not send any request at all in the latter case. Strange behaviour.

Anyhow, the other interfaces like openhab.app or greenT work perfectly.

With 1.7, you mean openHAB or HABdroid? As HABdroid is also on a higher version. But switching to a previous version is not an option.

**Comment by thoern** [comment]
I meant Habdroid 1.7.x.
I forgot to mention, that Webview works fine on the same Android-Mobile while using Classic-UI instead of Habdroid. 

So this combination works like a charm:
ClassicUIWebview -> https -> ReverseProxy -> OpenHAB

whereas this does not work:
habdroid Webview -> https -> ReverseProxy -> OpenHAB

The ReverseProxy is an Apache-Webserver which forwards the requests to OpenHAB.

**Comment by elisman** [comment]
Hi all,

this issue was fixed within #137. The bug was the same (duplicate). It should be also closed.

**Comment by nesys** [comment]
it seems there is the same issue on iOS

**Comment by eschizoid** [comment]
@nesys Yup, I'm having the same problem.
