### ISSUE TITLE
Add NFC info screen

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab-android#538]
The long-press action to write an action to an NFC tag comes as a surprise to new users.

I'd suggest to add a menu entry to the hamburger menu (e.g. "Write NFC tag") which simply described this function in a few words.

**Comment by ThomDietrich** [comment]
Sounds like you are on the right track!

Feel free to close this Issue in favor of an issue with the proposal by yourself.

**Comment by mueller-ma** [comment]
> but move the functionality there because

IMO it's better to have the long press action, because the sitemap is a structured and well-known representation of all items.
I have some improvements in mind: Add a new uri for item state changes (e.g. `openhab-icon://?i=item&s=state`). This way we can use two different receivers for nfc tags. The current one to open a sitemap and a worker to send the item updates. The current implementation for is opening the app, sending the update and closing the app, which is a quite bad ux IMO.
Mostly unrelated to nfc, but to the long press menu: Having the ability to share a chart or image. The share action should be located in the long press menu, so we have to add headers to this menu.

**Comment by mueller-ma** [comment]
An info screen can be added to read tags, clear tags and inform the user how to write new tags.

**Comment by mueller-ma** [comment]
> IMO it's better to have the long press action, because the sitemap is a structured and well-known representation of all items.

I didn't think at all the HABPanel-only users or that it might be useful to assign items that aren't used in a sitemap, e.g. assign an item that triggers a rule to do more advanced stuff.
I want to keep the possibility to write tags at the sitemap, but also add the possibility to get a full list of all items.

**Comment by mueller-ma** [comment]
I'm working on this.
