### ISSUE TITLE
Sitemap _default

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#577]
When selecting a sitemap the dialog always shows a sitemap called "_default". It should be displayed with a better looking name like "Things".
Or we remove it entirely, since it doesnt show up in basic ui.

**Comment by kaikreuzer** [comment]
I agree that this is probably better hidden - anyhow, it isn't really useful right now...

**Comment by lolodomo** [comment]
Except that in Basic UI we can access to it by updating the URL in the browser. In the Android app, if not available in UI, we will loose totally the access to this _default sitemap.
And if the user has not yet defined any sitemap, at least the _default sitemap allows to display something in the Android app.

**Comment by mueller-ma** [comment]
I vote for removing it entirely.

**Comment by FlorianSW** [comment]
We could have a condition, that if the _default sitemap is the only one, we can show it to the user in the selection dialog, otherwise remove it.

**Comment by lolodomo** [comment]
Looks like a better option.

**Comment by mueller-ma** [comment]
I dont think someone really uses this sitemap.

**Comment by kaikreuzer** [comment]
@mueller-ma I would agree with @FlorianSW and @lolodomo that removing it only if other sitemaps are available is the better option.
I admit that currently this sitemap is not very useful - but my hope would be that it will evolve in future to provide a "automatically inferred sitemap based on your Things and Items", so that it serves as a kind of quick-start fallback, especially for people that might do their setup with "simple linking" through the Paper UI.
