### ISSUE TITLE
Widgets for homescreen

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-android#6]
This was requested a couple of times on the mailinglist already, but nobody seemed to have cared to open an issue for it.
It would be great to be able to put a customizable widget directly on the Android homescreen - e.g. for an "All off" functionality or similar.
##

**Comment by cribskip** [comment]
Hey all, I'm working on it and see a prototype to be ready by next week - maybe need some help parsing the xml to get the items.

Please assign to me, @belovictor

**Comment by cribskip** [comment]
So, I've got my initial setup ready in my repo [cribskip/openhab.android branch "6-widget"](https://github.com/cribskip/openhab.android/tree/6-widgets).
It's initial so does not yet display user's items, just 2 out of the demo sitemap.
After selecting, user's able to choose action (standard one by now) and create a shortcut.

Would be glad if someone may point me on how to parse the items right. Problems I see are: "what label to set for the item?" and "how to parse xml?" ;)

**Comment by martinrunge** [comment]
I came across this issue while researching how to build a homescreen widget to display room temperature on a wall mounted tablet. Any progress on this? Does it make sense to implement my own solution?

**Comment by watou** [comment]
You might want to have a look at the new [HABPanel](https://community.openhab.org/t/habpanel-yet-another-implementation-of-a-no-frills-dashboard/12853) which works with OH1 and OH2 (but has more features in OH2).

**Comment by martinrunge** [comment]
looks great
@watou thank you for the hint

**Comment by redeye86** [comment]
Hi,

i am currently working on a homescreen widget imeplementation. It is still rather limited and only supports Switch-Items. But i try to improve it as i want to use it as a replacement for my "Deutsche Telekom Smart Home" System on my wall-mounted tablet. I added a Pin-Dialog with a code that can be specified in widget configuration. I use it for my alarm system. It is not really a secure solution as it is only used for that widget only and not for the app itself. But i think it should delay most intruders so that they exceed the grace period of my alarm system rules.

The code is still a bit buggy. If you add multiple widgets, all show the same thing. And the items need to be referenced somewhere in the sitemap "_default". Otherwise they are not updated on the homescreen when their states are changed from somewhere else.

You can find it here:
https://github.com/redeye86/openhab.android

Here are some screenshots:

![screenshot_20161106_194422](https://cloud.githubusercontent.com/assets/3612865/20040639/1a2c4f96-a45b-11e6-8a6f-5e6c7e6fac25.png)
![screenshot_20161106_194434](https://cloud.githubusercontent.com/assets/3612865/20040638/1a2b9542-a45b-11e6-8dd9-b9823f7fc511.png)
![screenshot_20161106_194447](https://cloud.githubusercontent.com/assets/3612865/20040640/1a2caf2c-a45b-11e6-89ed-59e7de0f24a2.png)
![screenshot_20161106_194938](https://cloud.githubusercontent.com/assets/3612865/20040641/1a2cc39a-a45b-11e6-9d99-549e000b3a06.png)

**Comment by kubawolanin** [comment]
@redeye86 sorry for resurrecting a year old thread but did you actually manage to create a pull request with your work? Would be awesome to see that in the app! :)

**Comment by redeye86** [comment]
Hi!

No, unfortunately not. The whole branch is a bit behind now and i would have to update the project metadata to make it use the current build tools and libraries, which would be feasible. But apart from that, the background service, which updates the widgets, still uses the long polling mechanism on the sitemap to get notified about item status updates. As far as i remember, you have to select a sitemap which includes the relevant items and the long polling http request returns as soon as any item from the sitemap is updated. So it gets many updates if you use a large sitemap and you also have some additional effort on the backend side to set it up. Personally, I use it on a wall mounted, continuously powered tablet, so it is ok for me. For general usage it would be much more efficient and convenient to have some mechanism that allows to register for changes on the individual items that are pushed to the client then. 

While it is ok to use this long polling for the relatively short time when the app is running in the foreground, I guess that the energy-saving subsystems in the newer android versions will shut down the background service sooner or later.

As far as I remember, I experimented with the websocket, comet, atmosphere or something-like-that api, but couldn't get it to work. I think support for some of the apis was discontinued and I also had some issues getting it to work on android. 

I am not aware of the current state of openhab and the cloud service. Is it possible to use gcm/fcm to get notified about status updates?

**Comment by mueller-ma** [comment]
> I am not aware of the current state of openhab and the cloud service. Is it possible to use gcm/fcm to get notified about status updates?

This isn't a very practical solution as widgets would only work when you have openhab cloud.

**Comment by redeye86** [comment]
Yes, but as far as i could see, notifications don't do either in that case. Maybe it makes sense to have two alternatives, one using gcm and the other one using a direct connection preferably for non-cloud installations (maybe also for notifications).

But I would contend that the latter wouldn't work well for mobile devices that are actually used on the go. They would need to reconnect to the openhab endpoint every time they (re)connect to another network. Battery drain and data usage would be considerable high while -at the same time- you are often unable to charge the phone and have to use metered networks. Most probably you also need to show a persistent notification to signalize the system not to shut down the background service when there is no more free ram (due to android's foreground service policy). This happens rarely on my wall-mount tablet, but it does! Even though it is typically idling on the homescreen.

**Comment by mueller-ma** [comment]
I have set up a foreground service for a broadcast listener. See #388
I use that branch and it doenst drain battery.

**Comment by robbyb67** [comment]
My current work-around is to setup an action with Tasker that makes a call to the openHAB REST api. Bit this is very insufficient because the is no way to get a feedback if the action was really successful.

**Comment by robbyb67** [comment]
A better solution than tasker is to use IFTTT button widgets together with openhab-cloud. This way you'll get feedback on the action.

**Comment by Misiu** [comment]
Anything going on with widgets support? Ideally, I'd like to have a simple switch for on/off actions and a static "label type" widget that could be used to display temperature. Take a look at eWeLink app, when You add widget You can choose the device that will be assigned with it, same can be done with Open HAB - user should be able to choose item from sitemap.
This thread is from 2014 and the last comment was more than a year ago.
@redeye86 do You think [Direct Boot support](https://github.com/openhab/openhab-android/issues/1168) would help?

**Comment by mueller-ma** [comment]
Maybe I'm missing something, but the blocking issue here is that the connection mobile => server is pretty easy, but server => mobile impossible (or at least impossible in an efficent way). Google wants us to use FCM to send updates from server to apps. To use GCM/FCM your openHAB server must be connected to openhab cloud. If you select an item for a widget, the app must send that to the server, so the server can send FCM messages on every item update. Implementing widgets means that the server, cloud and app must be updated.

However if you just want a switch that doesn't display the current value, it's more or less straight forward. Add an option ("add to home screen") to the long press menu of the items in the sitemap and create a widget if this option has been selected.

**Comment by Misiu** [comment]
@mueller-ma how communication from server to mobile is done right now? Via FCM?
From what I know Basic UI is using SSE (EventSource), is the same method used here?
I'll read a bit more about widgets and hopefully I'll find something useful.

**Comment by mueller-ma** [comment]
As long as the app is in foreground we use the rest api to get the sitemap and receive updates via SSE. Notifications are received via GCM (FCM's predecessor).
When the app is in the foreground, communication is quite easy and simple, but in the background there are limits by Android. One possibility would be using workers (minimum 15 minutes delay between updates) or a foreground service (persistent notifications and tons of "openHAB is using too much battery" warnings).
