### ISSUE TITLE
Change slider size according to screen size

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#653]
A user in the play store ask, if we could make the slider item larger, when using a tablet (or any device with a larger screen)

**Comment by mueller-ma** [comment]
We don't scale other elements as well, so I don't think we do it here.

**Comment by maniac103** [comment]
Hmm, but this actually might make sense though. It's also easy to implement.

**Comment by joepadmiraal** [comment]
I think this is a good idea because on a phone the sliders are currently too small to work efficiently.
On a Galaxy S8 my finger covers half the slider so I have no idea to what value I am changing things when I try to slide a slider.
When I hold the phone in landscape orientation there is a lot of unused space next to the sliders so it would be great if the sliders would become larger. This allows me to set the slider value more accurately.
