### ISSUE TITLE
Override xml values with own local values

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#708]
Whenever I need to pruge the app data, I have to fill local url, user, password and remote url, user, password in order to have the app working. My idea was to have a file, which is ignored by git, that contains these information. Gradle will use these information to replace the default values.

This will be also usefull for google mapview api key.

**Comment by cribskip** [comment]
Good idea. What about a QR code with the settings?
Users could create/view QR code on myopenhab.org with local and remote settings and print them (just like with the Fritz!Box) if they like.

Downside would be that the app then needs
- Camera permission (not critical anymore since this is nowadays a on-demand permission)
- QR parser and data handling

**Comment by mueller-ma** [comment]
Good idea. The app could use an external app to scan and parse the code. Can you open a new issue for that as it differs from this requested feature?

**Comment by mueller-ma** [comment]
> My idea was to have a file, which is ignored by git, that contains these information.

Acutally this is quite dangerous as someone builds an apk and may share their password. So I'm closing this for now.
