### ISSUE TITLE
Make basic ui theme default

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#713]
I personally like the basic ui theme more and that's also the outcome of a poll: https://community.openhab.org/t/basic-ui-like-themes-for-android-app/34208

We should rename and reorder the themes in the settings:
Bright (=basic ui)
Dark (=basic ui dark)
Black (=black/amoled)
Classic (=orange)
Classic dark (=current dark)

I disagree to migrate all users to the new theme, as some of them might tested it and switched back to orange.

**Comment by kaikreuzer** [comment]
Just some comment (sorry if I missed any previous discussions):

The "blue" from the Basic UI actually derives from Eclipse SmartHome (where blue is the primary color, see e.g. also its Paper UI).
The openHAB "corporate identity"/"style guide" is:
- orange as primary color
- blue as secondary/contrast color
(see the Paper UI or also https://docs.openhab.org/)

Independent of any polls or personal favorites, I would therefore very much suggest to use these colors as the default settings in any UI, so that the overall design is the same across the different UIs.

**Comment by maniac103** [comment]
The fact that the basic UI theme doesn't match the app (= OpenHAB icon) also backs the statement of @kaikreuzer

**Comment by mueller-ma** [comment]
> The fact that the basic UI theme doesn't match the app (= OpenHAB) icon

That's kind of true and the reason why I waited for the new icon to make this PR. With the old icon (Orange background) I would never changed the default theme to blue, but the current icon contains only one orange line, so it was "ok" for me.

 
> I would therefore very much suggest to use these colors as the default settings in any UI

Paper UI and Docs are only used for setup and only by the "computer guy" in a household. For daily usage most people use basic UI (orange theme exits, but not default), the apps (android is orange, ios mostly white/blue) or habpanel (different themes exist, but dark blue/grey is default), so the least UIs are currently orange.
Also IMO colors like orange or red look way more "agressive" than colors like blue or green (I've heard, that this is the reason why school boards are green).

@kaikreuzer I'm going to close this issue, but maybe we should discuss in openhab-core which color should be default for all uis, and open issues in every ui repo to change it to this default.

**Comment by kaikreuzer** [comment]
@mueller-ma I am about to start a website redesign and as a part of it I would like to get at least some simple style guide with a color palette out of it. Once this is there, it would make a lot of sense to address the different UIs.
