### ISSUE TITLE
Discovery failed error is shown after network reconnect

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab-android#755]
1. Open app
2. disable wifi
3. enable wifi
4. Discovery failed error is shown, even when a local url ist set

2.0.19-beta
Android 7.1.2

**Comment by FlorianSW** [comment]
The problem is: Once we get the "network changed" intent, it doesn't mean, that there's already an active (connected) internet connection. That makes the Reachability check fail with the local connection, even if the server is available in this network. As the local connection failed and there's probably no remote connection, the discovery is started.

I'll take a look how we can work around this, however a general solution (not only for WiFi networks, but also for VPN and so on) may be, that we have a higher timeout for the reachability check :(

**Comment by maniac103** [comment]
I think @mueller-ma is rather referring to the string of the error message which shouldn't state that we attempted discovery if we in fact didn't even try it. (I'd agree to that position)
