### ISSUE TITLE
Wrong charts are shown while loading

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-android#829]
Tested on 2.0.46-beta and seen on earlier betas as well (but not in 2.0.0 release):

When scrolling through a page with multiple charts, the app renders cached versions of the wrong chart until the new one is loaded - this causes a very irritating effect with charts being replaced by completely other charts:

![img_0063](https://user-images.githubusercontent.com/3244965/38503136-8eed1e56-3c11-11e8-93d7-e24f17acbea0.gif)

Similar to https://github.com/openhab/openhab-android/issues/826, but worse as it shuffles the charts.

**Comment by maniac103** [comment]
It's effectively the same thing as #826: ViewHolders get recycled and old image is continued to be shown until new image has finished loading. Not sure whether separate tracking really is useful...

(Working on completely replacing the SmartImageView already BTW. Just need to find a suitable drawable shown while loading the image...)

**Comment by mueller-ma** [comment]
> Just need to find a suitable drawable shown while loading the image...

You could reserve the space (at least for charts as they have a fixed size) and show a loading indicator.

**Comment by kaikreuzer** [comment]
I don't think a loading indicator is a solution for this. Once a page is loaded, I would not expect the charts/images being loaded and loaded again when merely scrolling through the page - the once loaded images should simply still be there (and not even be reloaded, unless they change).

Please have a look at the video: When I scroll up the page, the top most chart is wrong and gets reloaded - this imho must not happen.

**Comment by maniac103** [comment]
> don't think a loading indicator is a solution for this. Once a page is loaded, I would not expect the charts/images being loaded and loaded again when merely scrolling through the page - the once loaded images should simply still be there (and not even be reloaded, unless they change).

Yeah, that's right, the image cache should take care of this.

> Please have a look at the video: When I scroll up the page, the top most chart is wrong and gets reloaded - this imho must not happen.

I agree. I wonder what the best way to repro is though ... I guess I'll try with @mueller-ma's setup in #826 first.

**Comment by maniac103** [comment]
Thinking about it, the issue likely is https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/util/MySmartImageView.java#L128 in conjunction with https://github.com/openhab/openhab-android/blob/master/mobile/src/main/java/org/openhab/habdroid/util/MyWebImage.java#L56
Charts pass useImageCache as false, which is why a cached bitmap is *never* used for them. Instead, the useImageCache flag should only decide whether a new GET request is triggered in case a cached image is found. Perhaps we can even kill off that flag altogether and always use the cache, as charts are likely (@kaikreuzer or even guaranteed?) to have refresh set.

**Comment by kaikreuzer** [comment]
> or even guaranteed?

No, just likely.
